# Generated by Django 3.0.2 on 2020-01-12 13:51

import destinacija.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Agencije',
            },
        ),
        migrations.CreateModel(
            name='KategorijaDestinacije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='slike')),
            ],
            options={
                'verbose_name_plural': 'Kategorije Destinacija',
            },
        ),
        migrations.CreateModel(
            name='Zemlja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='slike')),
            ],
            options={
                'verbose_name_plural': 'Zemlje',
            },
        ),
        migrations.CreateModel(
            name='Destinacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('preporuka', models.BooleanField(default=False)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='slike')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinacija.KategorijaDestinacije')),
                ('zemlja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinacija.Zemlja')),
            ],
            options={
                'verbose_name_plural': 'Destinacije',
            },
        ),
        migrations.CreateModel(
            name='Cenovnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('broj_nocenja', models.CharField(max_length=100)),
                ('polasci', models.CharField(blank=True, max_length=100, null=True)),
                ('fajl', models.FileField(upload_to='cenovnici', validators=[destinacija.validators.validate_file_extension])),
                ('agencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinacija.Agencija')),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinacija.Destinacija')),
            ],
            options={
                'verbose_name_plural': 'Cenovnici',
            },
        ),
    ]
